"""Texts to use in labels in the GUI - Spanish"""
MESSAGE_BOX = ("Maitenotas versión 3\nProgramada por Taksan Tong\n"
               "Para uso libre y personal. Prohibida su venta o uso comercial\n"
               "Código fuente disponible en https://github.com/maitelab/maitenotas\n"
               "taksantong@gmail.com")
MESSAGE_BOX_TITLE ="Acerca de"
WELCOME = ("Bienvenido(a) a Maitenotas. En esta ventana aparecerán las notas de la hoja"
           " que elijas del árbol de la izquierda")
DIARY_NAME = "Defina un nombre para el diario"
INITIAL_NAME = "Nombre inicial"
BOOK_NAME = "Arbol"
NEW_LEAF = "Hoja nueva"
NEW_DIARY = "Nuevo diario"
DEFINE_PASSWORD = "Defina una contraseña a usar"
CONFIRM_PASSWORD = "Confirme contraseña a usar"
PASSWORDS_DO_NOT_MATCH = "Contraseñas no coinciden"
OPENING_DIARY = "Abriendo diario"
ENTER_PASSWORD = "Ingrese contraseña"
ERROR_READING_DATA = "Error leyendo datos"
LEAF_ONE_OF = "hoja 1 de "
LEAF_TWO_OF = "hoja 1 de "
SAMPLE_TEXT_1 = "texto ejemplo de hoja 1 de "
SAMPLE_TEXT_2 = "texto ejemplo de hoja 2 de "
INVALID_PASSWORD = "Contraseña inválida"
TEXT_ABOUT = "&Acerca de"
TEXT_QUIT = "&Salir\tCtrl+Q"
TEXT_ADD_LEAF = "&Agregar hoja\tCtrl+A"
TEXT_REMOVE_LEAF = "&Remover hoja\tCtrl+D"
TEXT_RENAME_LEAF = "&Renombrar hoja\tCtrl+R"
TEXT_APPLICATION = "&Aplicación"
TEXT_TREE ="&Arbol"
