"""Texts to use in labels in the GUI"""
MESSAGE_BOX = ("Maitenotas version 3\nBy Taksan Tong\n"
               "Free for personal use. Commercial use forbidden. Do not sale\n"
               "Source code available at https://github.com/maitelab/maitenotas\n"
               "taksantong@gmail.com")
MESSAGE_BOX_TITLE ="About"
WELCOME = ("Welcome to Maitenotas. This window shows the text of the selected leaf from"
           " the tree of the left section")
DIARY_NAME = "Enter a name for the diary"
INITIAL_NAME = "Initial name"
BOOK_NAME = "Tree"
NEW_LEAF = "New leaf"
NEW_DIARY = "New diary"
DEFINE_PASSWORD = "Define password to use"
CONFIRM_PASSWORD = "Confirm password to use"
PASSWORDS_DO_NOT_MATCH = "Passwords do not match"
OPENING_DIARY = "Opening diary"
ENTER_PASSWORD = "Enter password"
ERROR_READING_DATA = "Error reading data"
LEAF_ONE_OF = "Leaf 1 of "
LEAF_TWO_OF = "Leaf 2 of "
SAMPLE_TEXT_1 = "sample text 1 of "
SAMPLE_TEXT_2 = "sample text 2 of "
INVALID_PASSWORD = "Invalid password"
TEXT_ABOUT = "&About"
TEXT_QUIT = "&Quit\tCtrl+Q"
TEXT_ADD_LEAF = "&Add leaf\tCtrl+A"
TEXT_REMOVE_LEAF = "&Remove leaf\tCtrl+D"
TEXT_RENAME_LEAF = "&Rename leaf\tCtrl+R"
TEXT_APPLICATION = "&Application"
TEXT_TREE ="&Tree"
